version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    
    hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:2.3.0

    webserver:
        build: docker/airflow/
        image: tweets_airflow
        restart: always
        depends_on:
            - postgres        
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "8090:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    superset:
        container_name: superset
        build: docker/superset/
        image: tweets_superset
        restart: on-failure
        ports:
            - "8088:8088"

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        environment:
            - CLUSTER_NAME=test
        env_file:
            - docker/hive/hadoop-hive.env
        ports:
            - "50070:50070"

    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
        env_file:
            - docker/hive/hadoop-hive.env
        environment:
            SERVICE_PRECONDITION: "namenode:50070"
        ports:
            - "50075:50075"
            
    hive-server:
        image: bde2020/hive:2.3.2-postgresql-metastore
        env_file:
            - docker/hive/hadoop-hive.env
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
            SERVICE_PRECONDITION: "hive-metastore:9083"
        ports:
            - "10000:10000"

    hive-metastore:
        image: bde2020/hive:2.3.2-postgresql-metastore
        env_file:
            - docker/hive/hadoop-hive.env
        command: /opt/hive/bin/hive --service metastore
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
        ports:
            - "9083:9083"

    presto-coordinator:
        image: shawnzhu/prestodb:0.181
        ports:
            - "8081:8080"
    
    hadoop:
        build: docker/hadoop/
        image: tweets_hadoop
        ports:
            - "50010:50010"
            - "50020:50020"
            - "50090:50090"
            - "8089:8088"
            - "8020:8020"
            - "9000:9000"

    spark:
        build: docker/spark/
        image: tweets_spark_master
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - "8080:8080"
            - "7077:7077"
    spark-worker:
        build: docker/spark/
        image: tweets_spark_worker
        depends_on:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no